= Quarkus - Unleash
:extension-status: preview

include::./includes/attributes.adoc[]

https://unleash.github.io/[Unleash] is a feature toggle system, that gives you a great overview of all feature toggles across all your applications and services.
Quarkus Unleash extension is client for Unleash.

== Installation

If you want to use this extension, you need to add the `quarkiverse-unleash` extension first.
In your `pom.xml` file, add:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.unleash</groupId>
    <artifactId>quarkus-unleash</artifactId>
    <version>{project-version}</version>
</dependency>
----

== Usage

=== Unleash client

Assuming you have `Unleash` running on localhost:4242 you should add the following properties to your application.properties and fill in the values for url.

[source,properties]
----
quarkus.unleash.url=http://localhost:4242/api
----

Once you have configured the properties, you can start using an Unleash-client.

[source,java]
----
@ApplicationScoped
public class TestService {

    @Inject
    Unleash unleash;

    public boolean isTest() {
        return unleash.isEnabled("quarkus.unleash.test");
    }
}
----

=== @FeatureToggle

By using the `@FeatureToggle` annotation there is a shortcut to inject feature toggle.

[source,java]
----
@ApplicationScoped
public class TestService {

    @FeatureToggle(name = "my-toggle")
    Instance<Boolean> myToggle;

    @FeatureToggle(name = "my-toggle", defaultValue = true)
    Instance<Boolean> myToggleDefault;

}
----

[NOTE]
====
If the `@FeatureToggle` annotation is placed on a `boolean` field or method argument, an exception will be thrown at build time.
`@FeatureToggle` should only be used with the `Instance<Boolean>` type.
====

=== @FeatureVariant

By using the `@FeatureVariant` annotation there is a shortcut to inject feature toggle
variant or the payload of the variant.

[source,java]
----
@ApplicationScoped
public class TestService {

    @FeatureVariant(name = "toggle-variant")
    Instance<Variant> variant;

    @FeatureVariant(name = "toggle-payload")
    Instance<String> variant;

    @FeatureVariant(name = "toggle-variant-json")
    Instance<MyCustomJsonModel> variant;

}
----

=== Subscriber API

This extension supports the https://docs.getunleash.io/reference/sdks/java#subscriber-api[Subscriber API] from the Unleash Client SDK for Java.
It can be used by implementing the `UnleashSubscriber` interface as shown below.

[source,java]
----
import static io.getunleash.repository.FeatureToggleResponse.Status.CHANGED;

import java.util.HashMap;
import java.util.Map;
import java.util.Set;

import jakarta.enterprise.context.ApplicationScoped;

import io.getunleash.FeatureToggle;
import io.getunleash.event.UnleashSubscriber;
import io.getunleash.repository.FeatureToggleResponse;
import io.quarkus.arc.Unremovable;
import io.quarkus.logging.Log;

@ApplicationScoped // <1>
public class ToggleChangedLogger implements UnleashSubscriber {

    private static final Set<String> TOGGLE_NAMES = Set.of("my-toggle-1", "my-toggle-2");

    private final Map<String, Boolean> toggleValues = new HashMap<>();

    @Override
    public void togglesFetched(FeatureToggleResponse toggleResponse) {
        if (toggleResponse.getStatus() == CHANGED) {
            for (String toggleName : TOGGLE_NAMES) {
                FeatureToggle toggle = toggleResponse.getToggleCollection().getToggle(toggleName);
                if (toggle != null) {
                    Boolean previousValue = toggleValues.put(toggleName, toggle.isEnabled());
                    if (previousValue == null || previousValue != toggle.isEnabled()) {
                        String value = toggle.isEnabled() ? "enabled" : "disabled";
                        Log.infof("Feature toggle %s was just %s", toggleName, value);
                    }
                } else {
                    toggleValues.remove(toggleName);
                }
            }
        }
    }
}
----
<1> The `UnleashSubscriber` implementation has to be a CDI bean.

=== Bootstrapping toggles from a JSON string

This extension supports bootstrapping the Unleash feature toggles from a JSON string.
This can be especially useful for applications deployed in ephemeral containers where the access to the file system is sometimes restricted.
See the https://docs.getunleash.io/reference/sdks/java#bootstrapping[Unleash documentation] for more details about bootstrapping.

[source,java]
----
import jakarta.enterprise.context.ApplicationScoped;

import io.getunleash.repository.ToggleBootstrapProvider;
import io.quarkus.arc.Unremovable;

@ApplicationScoped // <1>
@Unremovable // <2>
public class TogglesBootstrapper implements ToggleBootstrapProvider {

    @Override
    public String read() {
        // Return a JSON string in the same format returned from /api/client/features <3>
    }
}
----
<1> The `ToggleBootstrapProvider` implementation has to be a CDI bean.
<2> The bean will be considered unused and will be automatically removed if it is not annotated with `@Unremovable`.
<3> Examples can be found in the https://github.com/Unleash/unleash-client-java/tree/main/src/test/resources[Unleash Client SDK for Java repository]

=== Testing
To use the test extension, add this dependency to the project:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.unleash</groupId>
    <artifactId>quarkus-unleash-test</artifactId>
    <version>{project-version}</version>
    <scope>test</scope>
</dependency>
----

`UnleashTestResource` creates an instance of admin and standard `Unleash` clients just for testing.
These instances are separate from the application instances.

[source,java]
----
@QuarkusTest
@QuarkusTestResource(UnleashTestResource.class)
public class BaseTest {

    @InjectUnleashAdmin
    UnleashAdmin admin;

    @InjectUnleash
    Unleash client;

    @Test
    public void test() {

        admin.toggleOff("toggle-1");
        admin.toggleOn("toggle-2");

        // wait for client change
        await().atLeast(12, SECONDS)
                .pollInterval(4, SECONDS)
                .until(() -> client.isEnabled("toggle-2"));

        boolean toggleOn = client.isEnabled("toggle-2");

        // ... test my application

    }
}
----

=== Dev-Services
Dev Services for Unleash is automatically enabled unless:

* `quarkus.unleash.devservices.enabled` is set to false
* `quarkus.unleash.url` is configured

Dev Service for Unleash relies on Docker to start the broker. If your environment does not support Docker, you will need
to start the broker manually, or connect to an already running broker. You can configure the broker address using
`quarkus.unleash.url`.

[[extension-configuration-reference]]
== Extension Configuration Reference

include::includes/quarkus-unleash.adoc[leveloffset=+1, opts=optional]
